import type {
  Course,
  LanternSeaItem,
  Member,
  Notice,
  PracticeLog,
  Product,
} from "@/lib/admin/types";

const now = new Date().toISOString();

export const productSeed: Product[] = [
  {
    id: "p-1",
    name: "修持經文扇",
    subtitle: "一開一合之間，讓心回到清明。",
    shortDescription: "扇面收錄短偈與觀息提示，讓日常也能成為溫柔修持。",
    description: "扇面收錄短偈與觀息提示，於一開一合之間提醒自己回到當下。",
    imageUrl: "/placeholder-image.svg",
    price: 280,
    meritPrice: 280,
    stock: 54,
    status: "active",
    category: "法物",
    moodTags: ["安定", "覺察", "智慧"],
    useCases: ["晨起靜坐", "閱讀經文", "午間收心"],
    meaning: "經文扇提醒我們，修持不必遠離生活，而是在每次起心動念時回到呼吸。",
    practiceMeaning: "當手勢慢下來，心念也會慢下來。這份節奏，正是專注與清明的開始。",
    practiceSteps: [
      "先讓呼吸平穩三次，感受肩頸慢慢放鬆。",
      "展扇默讀一句短偈，讓注意力回到當下。",
      "輕搧三到五下，觀察念頭起伏而不評判。",
      "收扇時默念今日願行，帶著清明回到日常。",
    ],
    contemplation: "今天的你，在哪一刻最容易分心？願你在下一次分心時，記得先回到呼吸。",
    energyAttributes: { stability: 4, wisdom: 5, focus: 4, healing: 3, balance: 4 },
    relatedProductIds: ["p-2", "p-3"],
    dedicationText: "願此法物流轉成為善念的橋樑，陪伴更多人於日常中安住清明。",
    createdAt: now,
    updatedAt: now,
    meritAmount: 280,
  },
  {
    id: "p-2",
    name: "觀息禪香",
    subtitle: "香息入心，讓情緒回到柔和。",
    shortDescription: "沉香與草本溫和調和，陪伴晨晚定課與夜間沉澱。",
    description: "沉香與草本溫和調和，作為晨晚定課的節拍，幫助身心沉靜。",
    imageUrl: "/placeholder-image.svg",
    price: 350,
    meritPrice: 350,
    stock: 8,
    status: "active",
    category: "香品",
    moodTags: ["療癒", "安定", "平衡"],
    useCases: ["冥想練習", "睡前安定", "情緒整理"],
    meaning: "香氣不是遮掩，而是提醒。提醒我們在紛擾之中，還能回到身體與呼吸。",
    practiceMeaning: "以香為節拍，幫助散亂心慢慢聚攏，重回安定的內在秩序。",
    practiceSteps: [
      "點香前先靜坐半分鐘，確認今日修持意圖。",
      "觀察第一縷香息，讓呼吸自然延長。",
      "在香氣中覺察身體緊繃處，輕輕放鬆。",
      "香末時向內道謝，回向這份安定給家人。",
    ],
    contemplation: "今天你最想照顧的情緒是什麼？請為它留一段不被打擾的呼吸。",
    energyAttributes: { stability: 4, wisdom: 3, focus: 3, healing: 5, balance: 4 },
    relatedProductIds: ["p-1", "p-3"],
    dedicationText: "願這縷香息，成為你與眾生之間溫柔而長久的祝福。",
    createdAt: now,
    updatedAt: now,
    meritAmount: 350,
  },
  {
    id: "p-3",
    name: "回向願心卡",
    subtitle: "將願心寫下，讓善念有方向。",
    shortDescription: "書寫每日願行與回向對象，讓修持延伸到他人福祉。",
    description: "書寫每日願行與回向對象，讓修持延伸到他人福祉。",
    imageUrl: "/placeholder-image.svg",
    price: 174,
    meritPrice: 174,
    stock: 9,
    status: "active",
    category: "文具",
    moodTags: ["安定", "提案", "專注"],
    useCases: ["書寫祈願", "課後反思", "睡前回向"],
    meaning: "願心卡是一種承諾，把心中善意落到具體行動，讓修持不只停留在想法。",
    practiceMeaning: "每日一念，長久就會成為習慣。願行被看見，修行便有了方向。",
    practiceSteps: [
      "先寫下今天最感恩的一件事。",
      "再寫下一個願行，越具體越好。",
      "選定回向對象，默念祝福三次。",
      "將卡片放在固定位置，提醒自己實踐。",
    ],
    contemplation: "今天的願行，是否與你真正重視的價值一致？",
    energyAttributes: { stability: 4, wisdom: 4, focus: 5, healing: 3, balance: 4 },
    relatedProductIds: ["p-1", "p-2"],
    dedicationText: "願每一張願心卡都承載真誠善念，讓更多生命因此獲得照亮。",
    createdAt: now,
    updatedAt: now,
    meritAmount: 174,
  },
];

export const lanternSeaSeed: LanternSeaItem[] = [
  {
    id: "l-1",
    title: "願心供燈",
    content: "以一盞燈，照見內在安定，將祝福回向給眾生。",
    imageUrl: "/placeholder-image.svg",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "l-2",
    title: "家人祈福燈",
    content: "為家人點一盞燈，願安康平順。",
    imageUrl: "/placeholder-image.svg",
    status: "inactive",
    createdAt: now,
    updatedAt: now,
  },
];

export const courseSeed: Course[] = [
  {
    id: "c-1",
    title: "晨間觀息 21 日",
    description: "由淺入深建立穩定呼吸與身心覺察。",
    date: "2026-06-05",
    time: "07:30",
    teacher: "明映老師",
    imageUrl: "/placeholder-image.svg",
    maxStudents: 40,
    status: "active",
    createdAt: now,
    updatedAt: now,
    signups: 36,
    category: "呼吸觀",
  },
  {
    id: "c-2",
    title: "晚課靜心引導",
    description: "每日 20 分鐘，安住當下。",
    date: "2026-06-08",
    time: "20:00",
    teacher: "行真老師",
    imageUrl: "/placeholder-image.svg",
    maxStudents: 30,
    status: "inactive",
    createdAt: now,
    updatedAt: now,
    signups: 18,
    category: "靜坐",
  },
];

export const memberSeed: Member[] = [
  {
    id: "m-1",
    name: "林清和",
    email: "qinghe@example.com",
    avatar: "",
    role: "admin",
    createdAt: now,
    level: "護持會員",
    joinedAt: "2025-10-12",
  },
  {
    id: "m-2",
    name: "張心月",
    email: "xinyue@example.com",
    avatar: "",
    role: "member",
    createdAt: now,
    level: "一般會員",
    joinedAt: "2026-01-04",
  },
];

export const practiceLogSeed: PracticeLog[] = [
  {
    id: "log-1",
    memberId: "m-1",
    title: "晨間觀息",
    content: "完成晨間 20 分鐘觀息與願文誦讀。",
    date: "2026-05-24",
    status: "done",
    createdAt: now,
    memberName: "林清和",
    practiceType: "觀息",
    courseName: "晨間觀息 21 日",
    reflection: "呼吸更穩，情緒起伏下降。",
  },
  {
    id: "log-2",
    memberId: "m-2",
    title: "晚間靜坐",
    content: "晚間靜坐 15 分鐘。",
    date: "2026-05-23",
    status: "in_progress",
    createdAt: now,
    memberName: "張心月",
    practiceType: "靜坐",
    courseName: "晚課靜心引導",
    reflection: "中段雜念多，後段較穩定。",
  },
];

export const noticeSeed: Notice[] = [
  {
    id: "n-1",
    title: "端午前夕共修通知",
    content: "本週五晚間 8 點於線上共修，歡迎提早 10 分鐘入場。",
    imageUrl: "/placeholder-image.svg",
    link: "/join",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "n-2",
    title: "新版修行簿功能預告",
    content: "即將上線修行目標與週報功能。",
    imageUrl: "/placeholder-image.svg",
    link: "/practice-notebook",
    status: "draft",
    createdAt: now,
    updatedAt: now,
  },
];
